source: /
paths:
  uploads: static/uploads
  static: static
collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: false
    preview:
      text:
      subtext:
      icon:
      icon_color:
      icon_background_color:
      image:
      metadata:
      gallery:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
editor:
  default_path: /uploads/default-editor-url.txt
timezone: Asia/Karachi
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
